### ISSUE TITLE
Bug? Player skin turned into black white model...

### ISSUE THREAD

**Issue by Kaisoul** [ArtixAllMighty/PetBuddy2016#8] opened 2016-11-11 13:21 UTC
well i started a new world and my player model keeps getting turned white with no details like it's a blank slate.  seems to happen when ever i change the skin of the Pet buddy.  would really love to know what is causing this or how to fix this issue as your mod looks like it would be fantastic in my Lan world.

**Comment by Kaisoul** [comment] 2016-11-11 13:26
should note i can't find the config file for this mod... dunno if that has anything to do with this...

**Comment by AbsolemJackdaw** [comment] 2016-11-11 16:10
the mod has no config file.
do you happen to have the log ? it might state something about connection problems.

also, my mod doesn't fiddle with the player skin, only with the pet buddy's skin, so I'd be surprised it's petbuddy mod that does that.

But seeing the log might help me to see what the problem is.

**Comment by Kaisoul** [comment] 2016-11-11 16:32
ok well i'll go pull my fml log and client log and put them as downloads on here since there size tends to be larger then a pastbin can handle

[logs.zip](https://github.com/ArtixAllMighty/PetBuddy2016/files/586245/logs.zip)

**Comment by Kaisoul** [comment] 2016-11-11 16:33
that is my fml latest, fml junk and normal log file from this morning zipped up for you.

**Comment by AbsolemJackdaw** [comment] 2016-11-11 22:27
The logs didn't tell me anything. 
does this only happen with my mod installed (remove it to note difference)?
does this happen with only petbuddy's installed(only star with petbuddy to note difference) ? 

i'm kinda baffled as to why your player skin woon't load. i'll try to take a look at it. but i can't promise anything

**Comment by Kaisoul** [comment] 2016-11-11 22:31
going to test out if it only happens with only your mod installed + your lib

**Comment by Kaisoul** [comment] 2016-11-11 22:32
but yea i couldn't find anything in my logs either though if memory serves me right i have heard of instances of graphical glitches like this from memory issues but i have minecraft loaded with 4g ram and can even load minecraft with a 128 resource pack though i play with soartex modded 64x resource pack.

**Comment by Kaisoul** [comment] 2016-11-11 22:38
ok your mod works fine with out other mods installed.   so considering i use around according to forge about 50-60 mods loaded   i think it was a texture memory problem.

**Comment by Kaisoul** [comment] 2016-11-11 22:39
though i have no clue why only happens with your mod or why it even would have that kind of issue unless minecraft has an issue with a heavy load of textures loaded.

**Comment by Kaisoul** [comment] 2016-11-11 22:40
gunna test your mod with my mods loaded but resource pack removed.

**Comment by Kaisoul** [comment] 2016-11-11 23:10
just unloaded my resource pack and still white textures so i leaning towards mod compatibility issue.  even tried F3+T  after i unloaded resource pack and still white texture

**Comment by Kaisoul** [comment] 2016-11-11 23:11
so to duplicate this insanity and hoping i am going to bundle up my mods/configs and the like so that it can be ripped apart to find this issue cause i really want to use your mod the pet looks to cute not to want to use em.

uploading my setup to my drop box then will link the zipped setup to here so if you wanted a copy of my setup maybe you can find this bug and possibly fix or at least tell me why it's happening.

**Comment by Kaisoul** [comment] 2016-11-12 02:21
https://dl.dropboxusercontent.com/u/16339019/Kaisoul%20modpack.zip

sorry about how long it took to upload this file.

**Comment by AbsolemJackdaw** [comment] 2016-11-12 12:52
Would you like to try something for me please ?
make a new world, don't change your pet buddy's skin. get a player skull from a command with the tag 'SkullOwner : subaraki' (or whatever friend's account name you know)

place down the skull.

The thing is, in my code, I use exactly the same processus as SkullBlocks to load in skins.
https://github.com/ArtixAllMighty/PetBuddy2016/blob/master/subaraki/petbuddy/entity/RenderPetBuddy.java#L79-L87

**Comment by Kaisoul** [comment] 2016-11-12 12:58
will try that and msg back in a few

**Comment by Kaisoul** [comment] 2016-11-12 13:16
ok i just did the command for a player skull x3
/give @p minecraft:skull 1 3 {SkullOwner:playername}
the names used was
subaraki               gave the correct head.
misha26               (GF) her head defaulted to female model head.... which is wrong she has a custom skin
kaisoul                  (me)  gave a blank white head......

**Comment by Kaisoul** [comment] 2016-11-12 13:17
i will go try and revisit main minecraft page and reinstall my custom skin... cause there should be no reason for this insanity....

**Comment by Kaisoul** [comment] 2016-11-12 13:31
ok did some further tests....

re-uploaded my skin to minecraft.net...   no effect on petbuddy mod
in another new world did the 3 skull test this time  GF & subaraki head was correct untill....

i made a name tag for each players name and tried them in the buddy...
the gui showed the correct skin model for GF & subaraki untill gui was closed and then buddy was still white & now player skulls are turned white.

**Comment by Kaisoul** [comment] 2016-11-12 13:59
hmm is it having problems with the uuid?    cause i looked at the usernamecashe & ussercashe
subaraki came up with 1 uuid
Misha26 came up with 2 different uuid
Kaisoul came up with 1 uuid
though.....
kaisoul666@gmail.com with it's own uuid
Kaisoul666@gmail.com again with it's own uuid
should note Kaisoul, kaisoul666@gmail.com & Kaisoul666@gmail.com   are all just me and should only be noted as Kaisoul with in PC minecraft

which that in and of it's self i don't understand.....  only thing i can think of is that the mod is possibly rendering an object with a null data entry?   mind you i do not know enough about the coding format to render an informed guess this is just a hunch based on how i am perceiving the information.

**Comment by AbsolemJackdaw** [comment] 2016-11-12 14:01
Might be a null object. problem may most likely lie within how I render the skin on the entity.
i'll try to solve this.
thanks for all the given information, it's all i needed !

**Comment by AbsolemJackdaw** [comment] 2016-11-12 21:30
I've added a beta release for pet buddy, with a fix. 
I don't know if it works, I can't test the bug on my own computer.
I've tried to prevent any null object, and copied the vanilla code (shame on me) instead of trying to make a shorter aproach to loading a skin.

tell me if the beta version fixes anything. (note, pets dont spawn anymore on login. you need to call it yourself)
thank you !

**Comment by Kaisoul** [comment] 2016-11-12 23:41
ok tested it the beta... but i crashed when i used a salmon to change the pet into a bear.
[crash-2016-11-12_17.36.10-client.txt](https://github.com/ArtixAllMighty/PetBuddy2016/files/587510/crash-2016-11-12_17.36.10-client.txt)

**Comment by AbsolemJackdaw** [comment] 2016-11-13 10:25
Fixed it. Shouldn't crash anymore when changing pet form.
new beta file released.

**Comment by Kaisoul** [comment] 2016-11-13 13:51
ok will test it shortly

**Comment by Kaisoul** [comment] 2016-11-13 14:06
tested it out i don't crash on pet skin change but... i start games with the null skin again...  this was tested in fresh worlds.

**Comment by crookedzro** [comment] 2016-11-13 17:07
I would have to say this problem you will have with the latest journeymap. Revert to journeymap-1.10.2-5.2.4-unlimited. And all your woes will go away. Using the latest beta will make your player and certain mobs have a white texture. Especially when using the PetBuddy mod.

**Comment by AbsolemJackdaw** [comment] 2016-11-13 18:42
:O

if the fix from crookedzro worked, please let me know and I'll close the issue. 
So glad it's not my mod doing this. I've been searching for hours !

**Comment by Kaisoul** [comment] 2016-11-13 20:59
will go hit up that fix in a sec
got family matters to hit up first

**Comment by Kaisoul** [comment] 2016-11-13 21:47
well using the beta and a reverted journey map   zero problems no more white texture issues

**Comment by AbsolemJackdaw** [comment] 2016-11-13 22:07
Thank you ! I blame journey map for this issue.
Marking it down as solved.

**Closed as completed by AbsolemJackdaw** 2016-11-13 22:07 UTC
